### ISSUE TITLE
Authentication and authorization on the server

### ISSUE THREAD

**Issue by kuredoro** [inno-nyan-dev/PetFood#21]
Token system: each API call needs a token.
Login system: users should login via their username and a password.
Database augmentation: tables to update.
If user relogins old token shall be revoked.

**Comment by Mexator** [comment]
There are several problems with the server, which I'd like to discuss:
- Server uses HTTP which is not safe for exchanging credentials. It is OK, while we're at localhost, but later it should be changed to HTTPS
- For the sake of designing mobile app UI I need to know what does `dangLevel` values stand for (it is a field in food model)
