### ISSUE TITLE
Fix Design Issues

### ISSUE THREAD

**Issue by Mexator** [inno-nyan-dev/PetFood#38]
As a User I want the design issues to be fixed so that I will like look of the app:
- [x] ProgressBar's of many screens have weird purple color
- [x] Font size on Details screen is too small
- [x] Error messages shown in Toast is a bit too small. I want to have dialog windows. Like this:
<img src=http://i.imgur.com/WXPa9Z0.png width=200/>
Dialog window should be always in the middle of screen. Even when keyboard is open, it should be drawn over it.

- [x] Fix screen titles (see in comments below)
- [x] Change name of app
- [x] Increase font size on Auth screens
- [x] Remove NOT IMPLEMENTED YET from drawer
- [x] Beautiful SearchBar

**Comment by ghost** [comment]
Screen names: 
- [x] `LoginFragment` => `Log in`
- [x] `FoodSearchFragment` => `Search Products`
- [x] `FoodDetailFragment` => name of displayed product

App name
- [x] `Rabbit Nutrition Handbook`

Labels
- [x] Change `Login` to `Log in` in the left drawer

**Comment by ghost** [comment]
## Wanted search bar
But with grey instead of black
![image](https://user-images.githubusercontent.com/8857825/117029633-830d5f00-ad07-11eb-8f31-554005184bad.png)

**Comment by ghost** [comment]
The empty label with danger level should not be shown until the screen with product details is completely loaded

**Comment by Mexator** [comment]
As you can see in newest release, this was fixed
