### ISSUE TITLE
Design app v1 UI

### ISSUE THREAD

**Issue by kuredoro** [inno-nyan-dev/PetFood#6]
There should be two screens
1) The food search
It should contain a vertical list of foods and a search bar on top of it. Favorite foods should also be accounted in the design.

2) The details screen
Just text (for now) or better....

The food is the real food, btw.

References:
Cat Dog Eat (literally our app!): https://play.google.com/store/apps/details?id=com.quagtech.candogseat.app&hl=en&gl=US
Barfastic (some *real* food here): https://play.google.com/store/apps/details?id=com.refactorizado.barfastic
A web-site that does what our app does kinda: https://www.foodsdogscaneat.com/?ref=producthunt
IDOL: https://play.google.com/store/apps/details?id=com.pawsm.mobile

**Comment by kuredoro** [comment]
Make it in Fluid UI.

**Comment by Mexator** [comment]
Reference for list:

<img src=https://user-images.githubusercontent.com/23018035/113694305-3cacec00-96d8-11eb-853c-8a09126e084d.jpg width=300>
